{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heal.fullname" . }}-api
  labels:
    {{- include "heal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "heal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
{{- end }}
