"""add scheduling lease columns

Revision ID: 14fd0b504525
Revises: a37a06b022a1
Create Date: 2026-08-30 16:48:58.940962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fd0b504525'
down_revision: Union[str, Sequence[str], None] = 'a37a06b022a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('suspicious_streak', sa.Integer(), nullable=False))
    op.add_column('sites', sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('locked_by', sa.String(length=64), nullable=True))
    op.add_column('sites', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sites_locked_until'), 'sites', ['locked_until'], unique=False)
    op.create_index(op.f('ix_sites_next_check_at'), 'sites', ['next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_next_check_at'), table_name='sites')
    op.drop_index(op.f('ix_sites_locked_until'), table_name='sites')
    op.drop_column('sites', 'locked_until')
    op.drop_column('sites', 'locked_by')
    op.drop_column('sites', 'next_check_at')
    op.drop_column('sites', 'suspicious_streak')
    # ### end Alembic commands ###
