"""add sites table

Revision ID: a37a06b022a1
Revises:
Create Date: 2026-08-30 16:22:43.257539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37a06b022a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fqdn', sa.String(length=253), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('influxdb_tag', sa.String(length=64), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('enabled_probe_types', sa.JSON(), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('http_path', sa.String(length=2048), nullable=False),
    sa.Column('expected_status_codes', sa.JSON(), nullable=False),
    sa.Column('tcp_ports', sa.JSON(), nullable=False),
    sa.Column('last_status', sa.Enum('HEALTHY', 'DEGRADED', 'UNREACHABLE', 'DNS_FAILED', 'TIMEOUT', 'CONNECTION_REFUSED', 'TLS_FAILED', 'HTTP_ERROR', 'SUSPECTED_FILTERED', 'UNKNOWN', name='sitestatus', native_enum=False, length=32), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    op.create_index(op.f('ix_sites_fqdn'), 'sites', ['fqdn'], unique=True)
    op.create_index(op.f('ix_sites_influxdb_tag'), 'sites', ['influxdb_tag'], unique=True)
    op.create_index(op.f('ix_sites_is_active'), 'sites', ['is_active'], unique=False)
    op.create_index(op.f('ix_sites_last_status'), 'sites', ['last_status'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_last_status'), table_name='sites')
    op.drop_index(op.f('ix_sites_is_active'), table_name='sites')
    op.drop_index(op.f('ix_sites_influxdb_tag'), table_name='sites')
    op.drop_index(op.f('ix_sites_fqdn'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
